name: KamaCache CI

on:
  push:
    branches: [ main, feat/v2 ]
  pull_request:
    branches: [ main, feat/v2 ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      etcd:
        image: quay.io/coreos/etcd:v3.5.0
        ports:
          - 2379:2379
          - 2380:2380
        options: >-
          --name etcd
          -e ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
          -e ETCD_ADVERTISE_CLIENT_URLS=http://localhost:2379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Install dependencies
        run: go mod tidy

      - name: Run all tests
        run: go test -v ./...
